### ISSUE TITLE
Enhancements for dutch language

### ISSUE THREAD

**Issue by ziggyke** [jeevatkm/ReplyWithHeader#100]
I've checked the source and found in:
ReplyWithHeader/ReplyWithHeader/Resources/nl.lproj/MailHeader.strings

The following:
```
    "STRING_DATE" = "Datum";
    "STRING_REPLY_TO" = "Reply-To";
    "STRING_SENT" = "Datum";
    "STRING_WROTE" = "het volgende geschreven";
    "STRING_FORWARDED_MESSAGE" = "het volgende geschreven";
    "STRING_UPDATE_WINDOW_SUBTITLE" = "Een nieuwe versie van %@ beschikbaar!";
```

It should be:
```
    "STRING_DATE" = "Ontvangen"; (because I think you mean the date that the mail has been received or am I wrong? And if you change this, will it affect the code/layout in config.plist?)
    "STRING_REPLY_TO" = "Antwoorden Aan";
    "STRING_SENT" = "Verzonden"; (because I think you mean the date that the mail has been send or am I wrong? And if you change this, will it affect the code/layout in config.plist?)
    "STRING_WROTE" = "Geschreven:";
    "STRING_FORWARDED_MESSAGE" = "Doorgestuurd bericht:";
    "STRING_UPDATE_WINDOW_SUBTITLE" = "Een nieuwe versie van %@ is beschikbaar!";
```

Thanks to take a look into this and change it, if you want.

**Comment by jeevatkm** [comment]
Thanks for your help @ziggyke 

I can update this one straight away-
```
"STRING_UPDATE_WINDOW_SUBTITLE" = "Een nieuwe versie van %@ is beschikbaar!";
```

However, I have to cross check with `Mail.app` internal values for (since it's used for header manipulation) -
```
"STRING_DATE" = "Datum";
"STRING_REPLY_TO" = "Reply-To";
"STRING_SENT" = "Datum";
"STRING_WROTE" = "het volgende geschreven";
"STRING_FORWARDED_MESSAGE" = "het volgende geschreven";
```

I took these values from `Mail.app` long ago.

**Comment by ziggyke** [comment]
You're welcome.
Thanks that you would like to investigate this, Can I check in Mail.app for the values or do you have a dutch system available?

If you need help in this I'm glade to help.

**Comment by jeevatkm** [comment]
I don't have dutch system, I use `en-US`. 

I use this [languageswitcher app](http://www.tj-hd.co.uk/en-gb/languageswitcher/) for localization testing.

**Comment by jeevatkm** [comment]
I have updated window subtitle with v5.2-beta. you can download it right away.

**Comment by jeevatkm** [comment]
Closing it for v5.2 release.
