### ISSUE TITLE
5.2-beta localization error in FR in SierraOs

### ISSUE THREAD

**Issue by f4hla** [jeevatkm/ReplyWithHeader#101]
Hi
got message 
"ReplyWithHeader v5.2-beta is currently not supported in your Locale[ français (France)(fr-FR) ] it may not work as expected, so disabling it.
Please contact plugin author - https://github.com/jeevatkm/ReplyWithHeader/issues."

Found in MailHeader.m that this is localizations naming mismatch probably with the os update (change to be done in  localeIdentifier?)
Thanks

**Comment by jeevatkm** [comment]
@f4hla  thanks for reporting it. Apple made changes(correct legacy issues) in localization is Mail.app. I'm aware of this issue and working on it. Thanks for your patience.

**Comment by insekt** [comment]
The same problem with Russian.

**Comment by ziggyke** [comment]
Also check other issues, before posting a new one. 
#98 is already about this topic.

I've just posted this in it:
As workaround you can do this:
Install [languageswitcher app](http://www.tj-hd.co.uk/en-gb/languageswitcher/) for changing the localization of the mail.app to English (if wanted you can configure it that it always open in English.

Then you need to go to:
Mail -> Preferences -> RWH -> enable it (your previous settings remain untouched)

If that s set when you perform a reply (all)/Forward then the headers are still in the correct language of your overal system.

Hopefully this will help others and maybe jeevatkm to pin point where the issue might be to solve it.
I was sick of not getting my beautiful headers, that I tried this methode and it works for me.

**Comment by jeevatkm** [comment]
Done! will be released in v5.2 this weekend, for now updating v5.2-beta. you can download it right away.

**Comment by jeevatkm** [comment]
Closing it for v5.2 release.
