### ISSUE TITLE
Mail.app hangs on reply or forward when a previously configured font is missing

### ISSUE THREAD

**Issue by GHubbler** [jeevatkm/ReplyWithHeader#102]
I had set the font for RWH to Tahoma and had it installed as system wide available.
Now, I cleaned all the old MS Office stuff from my Mac and did a fresh install of Office 2016. In Office the fonts are available in the apps, but not on system level.

RWH had now an old entry to a font that no longer exists. When replying or forwarding a mail Mail.app just hangs. In Console there is also a corresponding message of an unhandled reference to a nil value.

Suggestion: Check for existence of the configured font on startup with an error message if it is not existent any more or set this to an available (default) system font as a fallback.

**Comment by ziggyke** [comment]
Nice suggestion, I assume it is solved by changing the font to another one in the preferences of RWH?

**Comment by jeevatkm** [comment]
I will update the default font to Helvetica in v5.2 release. Then user can choose the font they like for headers. Thanks for reporting.

**Comment by jeevatkm** [comment]
Done! will be released in v5.2

**Comment by jeevatkm** [comment]
Done! will be released in v5.2 this weekend, for now updating v5.2-beta. you can download it right away.

**Comment by ronedwards** [comment]
Thanks, I changed the Main Message Font from Calibri to Helvetica. That didn’t work - that the font you mean or the RWH Header Typography?

Thanks
R

**Comment by ziggyke** [comment]
I ment the font of RWH header.

**Comment by ronedwards** [comment]
Yep, changed it to Helvetica, makes no difference!

https://www.dropbox.com/s/6e4z47618sy6rbx/Mail%20Crash.rtf?dl=0

![screenshot 2016-10-20 16 26 00](https://cloud.githubusercontent.com/assets/22950132/19547799/00c7d0ce-96e2-11e6-9617-eb949676f895.png)

**Comment by jeevatkm** [comment]
Closing it for v5.2 release.

**Comment by GHubbler** [comment]
In my opinion there should be also a check, if a selected font is available or not. Without this might become a security issue.

**Comment by jeevatkm** [comment]
@GHubbler user will be able to select only available fonts from system. That's I have defaulted to system available font instead of `Tahoma`.

Can you please describe about security issue you mentioned about?

**Comment by GHubbler** [comment]
I have learned: All and every input is eval. So, I have to check, that functions are only in defined states. Checking variables to nil, null or nothing is the first check to avoid undefined application behavior. If a user can delete a previously defined or the default font the application becomes in an undefined state and those opens the door to further implied actions. And if I can avoid those undefined condition with a simple check, I would do so. ;)
