### ISSUE TITLE
Enhance simple date format 

### ISSUE THREAD

**Issue by jeevatkm** [jeevatkm/ReplyWithHeader#104]
Conversation from Disqus: Catherine Mimeau

Hi! Thank you so much for this plugin! I have a question about the date format. I use French and the format I get is this: "Date d'envoi: 26 septembre 2016 11:04:00 UTC−3". Is there a way to get something simpler, like this: "Date d'envoi: 26 septembre 2016 11:04"? I tried changing my regional settings but nothing changed in Mail. Thank you!

---

Apple default date format based on system: 
The date format is the same as with RWH: "Date: 27 septembre 2016 13:53:24 UTC−3". 

---

Thanks a lot for this update!

When I use the simple format (in French), I get something like this:
jeudi, oct. 20, 2016 at 12:31:14 AM

When I use the international format, I get this:
20 octobre 2016 à 03:31:14 UTC

So I see a few problems with the simple format... First, it would be nicer if the first letter was capitalized (Jeudi). Also, in French, the number comes before the month and I would rather have the full month and no comma before the year (20 octobre 2016). For the time, it should be "à" and not "at" and I would rather not have the seconds or AM/PM (I would prefer a 24 hour clock). So the ideal format for me would be: "Jeudi, 20 octobre 2016 à 00:31". I would also be happy without the day: "20 octobre 2016 à 00:31".

Now, I realize that those are A LOT of changes that I am asking! They also reflect my own preferences and the French date format, so I am not sure how well you can incorporate them to your plugin. I guess that the ideal solution would be that the date format corresponds to our system preferences, but I have no idea whether this is doable...

Anyway, I will be using the international format for now, and I would love to help some more if you need me to, but it would also be fine for me if you decided not to update the date format further. Thank you again so much for your plugin!

**Comment by ziggyke** [comment]
I can confirm that RWH v5.3 beta fixes this issue.
You can download it at issue #109

**Comment by jeevatkm** [comment]
RWH uses OS date and format settings. I'm particularly manipulating date format. I'm closing this and leaving a choice to user.
