### ISSUE TITLE
Manage signatures void selection

### ISSUE THREAD

**Issue by Stradivaria** [jeevatkm/ReplyWithHeader#105]
Since updating from El Capitan to macOS Sierra, the selection list "Manage signatures" stays empty. This occurred both under RWH 5.2 bèta and the final release 5.2.
Under El Capitan, the mail accounts and signatures showed up correctly.
Removing and (re-)adding signatures didn't change this behavior.

![rwh sig](https://cloud.githubusercontent.com/assets/23047450/19696099/1b18b81e-9ae6-11e6-9a92-622924ac18ce.jpg)

**Comment by jeevatkm** [comment]
Do you see any errors in Console.app from Mail.app?

**Comment by Stradivaria** [comment]
Not sure what to look for.
This item comes quite often : not switching as we're not in ~/Library/Keychains/: /Library/Keychains/System.keychain (0)
Don’t know if it has somehow to do with…

KR,
Nico

**Comment by Stradivaria** [comment]
_Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'missing variable binding for (null)'
abort() called
terminating with uncaught exception of type NSException_

Related to RWH?
A detailed error report available via PM.

**Comment by Stradivaria** [comment]
Mail[20166]: MailHeader.m: 111 ReplyWithHeader v5.2 - Is locale supported: YES
Mail[20166]: MHPreferences.m: 221 signatures: (null)

**Comment by Stradivaria** [comment]
MHPreferences.m: 221 signatures: (null)
Mail[37457]: MHPreferences.m: 367 firstIndex -1, lastIndex -1
Mail[37457]: MHPreferences.m: 296 Account [(null), MH-S-(null)]: (null)
Mail[37457]: RWH: Signature mapping doesn't exist
Mail[37457]: MHPreferences.m: 367 firstIndex -1, lastIndex -1
Mail[37457]: MHPreferences.m: 296 Account [(null), MH-S-(null)]: (null)
Mail[37457]: RWH: Signature mapping doesn't exist

**Comment by gringott** [comment]
Any update on this issue? Is it sorted meanwhile?

**Comment by Stradivaria** [comment]
status quo

**Comment by jeevatkm** [comment]
@Stradivaria , @gringott I'm sorry, I got busy with my personal work. I will try to work on as soon as possible. Thanks for your patience.

**Comment by ziggyke** [comment]
I can confirm that RWH v5.3 beta fixes this issue.
You can download it at issue #109

**Comment by jeevatkm** [comment]
@ziggyke thank you for testing signature as well.
