### ISSUE TITLE
Doesn't work with all accounts

### ISSUE THREAD

**Issue by 22431364** [jeevatkm/ReplyWithHeader#106]
Hi,

RWH works okay with my @live.com account but doesn't work with the other accounts that I have linked to Mail.

Is there a config that I need to do or some other setting?

Thanks in advance.

**Comment by jeevatkm** [comment]
@22431364 Can you please check console.app for any error info? RWH works with all the mail accounts (myself using iCloud, Gmail, outlook, Exchange accounts).

There is a known is with OS serria mail.app doesn't work for signatures. I caught up in my personal family issues, as of now I'm unable to work on. I will do as soon as I get a time.

**Comment by jeevatkm** [comment]
Closing it
