### ISSUE TITLE
On "date", "author" wrote:

### ISSUE THREAD

**Issue by sickidolderivative** [jeevatkm/ReplyWithHeader#107]
Hi

When replying to emails I get the "On 28 Feb 2017, at 10:58, Name Lastname <email@address> wrote:" line below the proper RWH header. Is there a way to remove it? 

I'm using Mail 10.2 on MacOS Sierra.  

Thanks!

**Comment by jeevatkm** [comment]
Is RWH plugin is active in your Mail preferences? Can you please verify it?

Whenever you update the OS X, apple deactivates the third party plugins. So you need to re-run the installer as mentioned in [FAQ](https://myjeeva.com/replywithheader#faq).

**Comment by sickidolderivative** [comment]
Yes, the plugin is active. It's a fresh install - the plugin was installed just few days ago. The plugin is working, as it generates the RWH header. The "On <Date>, <Author> wrote:" line appears below the RWH header.

**Comment by jeevatkm** [comment]
Okay, understood. Can you please share your RWH mail preferences screenshot?

Also can you please keep eye on Console.app for any errors from Mail.app while doing Reply/Forward? If any please post it here.

**Comment by sickidolderivative** [comment]
Please find the screenshot of the settings: https://www.dropbox.com/s/efll50wkg4429oa/Screen%20Shot%202017-02-28%20at%2021.53.39.png?dl=0

**Comment by jeevatkm** [comment]
Thanks for the screenshot. 

Can you also help me with error info from console.app? Because Mail.app or RWH plugin surely logs if anything goes wrong. It helps me to understand the problem, so I can fix or give you a suggestion.

**Comment by sickidolderivative** [comment]
Below are errors and faults found when searching for "Mail.app", yet no entries are generated when invoking reply or forward.
   
==== XPC handleXPCMessage XPC_ERROR_CONNECTION_INVALID

Failed to read values in CFPrefsPlistSource<0x600000ae5900> (Domain: com.apple.PowerManagement, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): accessing preferences outside an application's container requires user-preference-read or file-read-data sandbox access, detaching from cfprefsd

Detected missing constraints for <private>.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you. If this view is laid out manually on macOS 10.12 and later, you may choose to not call [super layout] from your override. Set a breakpoint on DETECTED_MISSING_CONSTRAINTS to debug. This error will only be logged once.

warning: dynamic accessors failed to find @property implementation for 'uniqueId' for entity ABCDInfo while resolving selector 'uniqueId' on class 'ABCDInfo'.  Did you remember to declare it @dynamic or @synthesized in the @implementation ?

warning: dynamic accessors failed to find @property implementation for 'linkId' for entity ABCDContact while resolving selector 'linkId' on class 'ABCDContact'.  Did you remember to declare it @dynamic or @synthesized in the @implementation ?

**Comment by sickidolderivative** [comment]
Is there any hope?

**Comment by jeevatkm** [comment]
Thanks for sharing error info. This error is not belongs to RWH. 

As of today I have not updated my MacBook to mail.app v10.2, let me give it try at my end and get back to you.

If I'm unable to find any, are you okay to do screen sharing session with me to do analyze the issue?

**Comment by ziggyke** [comment]
Have you tried by disabling/uninstalling other mail plugins which may interfere with RWH?
Otherwise try to use the new RWH v5.3 beta downloadable in issue #109 

At this moment I don't have any issue with the new beta RWH v5.3

**Comment by jeevatkm** [comment]
Thanks @ziggyke
