### ISSUE TITLE
Crashes with Sierra 10.12.4 on ReplyAll

### ISSUE THREAD

**Issue by michelef** [jeevatkm/ReplyWithHeader#109]
Hi,
It crashes in Sierra 10.2.4 when Replying to ALL.
Reply to a single individual seems to work well.

Process:               Mail [74052]
Path:                  /Applications/Mail.app/Contents/MacOS/Mail
Identifier:            com.apple.mail
Version:               10.3 (3273)
Build Info:            Mail-3273000000000000~1
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Mail [74052]
User ID:               501

Date/Time:             2017-03-28 10:56:50.832 -0400
OS Version:            Mac OS X 10.12.4 (16E195)
Report Version:        12
Anonymous UUID:        55A218F0-2B57-EDFF-894E-6049BC04B05C

Sleep/Wake UUID:       0E551FD2-693C-4DAB-AD9D-C09948C59F10

Time Awake Since Boot: 75000 seconds
Time Since Wake:       36000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
Crashing on exception: *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fffccdf262b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fffe219f1da objc_exception_throw + 48
2   CoreFoundation                      0x00007fffccd0e50d -[__NSArrayM insertObject:atIndex:] + 1389
3   ReplyWithHeader                     0x000000010fb37836 ReplyWithHeader + 51254
4   ReplyWithHeader                     0x000000010fb37348 ReplyWithHeader + 49992
5   ReplyWithHeader                     0x000000010fb36c68 ReplyWithHeader + 48232
6   Mail                                0x000000010b038cdb Mail + 1092827
7   Mail                                0x000000010af8ac07 Mail + 379911
8   MailUI                              0x00007fffdc8cc2fd __58-[MUIWKWebViewController generateStyleInlinedWebDocument:]_block_invoke_2 + 558
9   CoreFoundation                      0x00007fffccd670ac __invoking___ + 140
10  CoreFoundation                      0x00007fffccd66f31 -[NSInvocation invoke] + 289
11  WebKit                              0x00007fffd5654c37 -[_WKRemoteObjectRegistry _callReplyWithID:blockInvocation:] + 317
12  WebKit                              0x00007fffd5746e1f _ZN3IPC13handleMessageIN8Messages20RemoteObjectRegistry14CallReplyBlockEN6WebKit20RemoteObjectRegistryEMS5_FvyRKNS4_8UserDataEEEEvRNS_7DecoderEPT0_T1_ + 96
13  WebKit                              0x00007fffd56ae1b7 _ZN3IPC18MessageReceiverMap15dispatchMessageERNS_10ConnectionERNS_7DecoderE + 129
14  WebKit                              0x00007fffd585dad0 _ZN6WebKit15WebProcessProxy17didReceiveMessageERN3IPC10ConnectionERNS1_7DecoderE + 46
15  WebKit                              0x00007fffd5675a09 _ZN3IPC10Connection15dispatchMessageENSt3__110unique_ptrINS_7DecoderENS1_14default_deleteIS3_EEEE + 119
16  WebKit                              0x00007fffd567869d _ZN3IPC10Connection18dispatchOneMessageEv + 175
17  JavaScriptCore                      0x00007fffcfd7d2a9 _ZN3WTF7RunLoop11performWorkEv + 169
18  JavaScriptCore                      0x00007fffcfd7d562 _ZN3WTF7RunLoop11performWorkEPv + 34
19  CoreFoundation                      0x00007fffccd893b1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
20  CoreFoundation                      0x00007fffccd6a63c __CFRunLoopDoSources0 + 556
21  CoreFoundation                      0x00007fffccd69b26 __CFRunLoopRun + 934
22  CoreFoundation                      0x00007fffccd69524 CFRunLoopRunSpecific + 420
23  HIToolbox                           0x00007fffcc2c9ebc RunCurrentEventLoopInMode + 240
24  HIToolbox                           0x00007fffcc2c9bf9 ReceiveNextEventCommon + 184
25  HIToolbox                           0x00007fffcc2c9b26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
26  AppKit                              0x00007fffca864e24 _DPSNextEvent + 1120
27  AppKit                              0x00007fffcafe085e -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
28  AppKit                              0x00007fffca8597ab -[NSApplication run] + 926
29  AppKit                              0x00007fffca8241de NSApplicationMain + 1237
30  libdyld.dylib                       0x00007fffe2a80235 start + 1

**Comment by jeevatkm** [comment]
@michelef It seems you're 10.12.4 version. In OS 10.12.4 Apple brings breaking changes. I'm working on it.

Could you please help me out for the Testing once I'm done with changes?

**Comment by michelef** [comment]
Sure. I'll be very happy to help.
And thanks for the prompt reply
Michele

**Comment by jeevatkm** [comment]
Thank you.

**Comment by MrO007** [comment]
Hey, I don't get a crash on Reply/Reply-All.  Only unresponsive Reply/Reply-All buttons.

Cheers,
Mike

**Comment by networkjitter** [comment]
I am only having an issue with reply all, reply seems to work just fine.

-Aaron

**Comment by michelef** [comment]
Yes, me too, only ReplyAll

**Comment by jeevatkm** [comment]
@MrO007 @michelef @networkjitter Thank you for your inputs.

**Comment by jeevatkm** [comment]
@michelef @MrO007 @networkjitter I have prepared the RWH v5.3 beta. Please test it at your end and let me know the feedback. Then I will make a public release.

Download link: http://bit.ly/2nFIxyw

**Comment by ziggyke** [comment]
I've tested RWH v5.3 beta and reply all is fixed, but also not changing the headers with multiple signatures! It works perfect again!

**Comment by gcabanac** [comment]
I concur: the crash no longer occurs with Reply All :-) 
Thanks :-)

**Comment by jeevatkm** [comment]
Thank you @ziggyke @gcabanac for your confirmation. I will make a public release.
