### ISSUE TITLE
RWH Apple Mail

### ISSUE THREAD

**Issue by Fatness7** [jeevatkm/ReplyWithHeader#111]
I am experiencing problems after restarting I will try to reply to an email and the header doesn't get added, the recipient removed and then I can't close the window - then I restart again. I am only able to reply to 1 or 2 emails before the error happens again.

**Comment by Fatness7** [comment]
OS Version: 10.12.5 (16F73)
RWH Version: 5.3
Any Plugins other than RWH: MailButler Installed version 6872
Error Details of RWH from Console.app:

**Comment by Fatness7** [comment]
Please disregard - MailButler plugin is the problem. I disabled and the problem has stopped.

**Comment by Fatness7** [comment]
It is still happening but I don't see anything related to RWH in the console.app..

**Comment by jeevatkm** [comment]
Your version details is exactly same as my machine. 

Can you please uninstall Mailbulter and do fresh install of RWH v5.3 then try out?

I will would like to remove possibilities while debugging. Also RWH will sure log error if anything goes especially your scenario.

**Comment by jeevatkm** [comment]
Closing it. Thanks.
