### ISSUE TITLE
macOS High Sierra is released

### ISSUE THREAD

**Issue by jeevatkm** [jeevatkm/ReplyWithHeader#112]
Test RWH and add compatibility if it breaks :)

**Comment by macjeff** [comment]
Definitely 5.3 wont run under High Sierra.  

Is there a 5.4 beta yet?

**Comment by jeevatkm** [comment]
@macjeff Thanks for your feedback. 

This week I'm planning to install beta version and work on RWH. Pretty packed with my day work.

Once v5.4-beta is ready then I will ping you here.

**Comment by jeevatkm** [comment]
I was working on RWH 5.4-beta. Last week my MacBook crashed. It's currently in Apple Service. As soon as I get it back. I will resume my work. I'm sorry about the delay. Thank you for your patience.

**Comment by jeevatkm** [comment]
This morning I got my macbook back. Logic board got replaced. 

High Sierra beta mail.app has lot of internal changes Apple brought it in. RWH breaks in all three key functionality Reply, Reply All and Forward.

I'm woking on it, will fix every breaking changes. Thanks for your support.

**Comment by jeevatkm** [comment]
Dear All - I know, apple has released the high sierra today. This OS has many internal changes in Mail.app. I'm working on it make RWH fully compatible with High Sierra.

Looking forward to your support and thank you for your patience.

**Comment by jeevatkm** [comment]
I have made RWH work with High Sierra 10.13. However RWH mail preference UI cut off. Need to work.

Good news is RWH functionality is ready to use with high sierra.

**Comment by macjeff** [comment]
I have another request and maybe you have a way around it.  I do seed testing for Apple so I am RARELY on the current OS version.   All my mail plugins wont work.  99% of them work fine but they have the up to this version set so it wont work under any versions past that.   Could you post a version without that check for people doing testing?  That way I can enjoy some of the features!!!  A warning would be fine that if Mail Crashes remove the plugin.  If someone is testing beta OS they should know that much.     LOL

**Comment by funnel20** [comment]
Hi,
Is the project discontinued, or is there any hope for High Sierra?

**Comment by jeevatkm** [comment]
@funnel20 RWH is very much active and I'm maintaining it. Its just Apple made the life little harder then before.

`v5.4-beta` was released few weeks ago with High Sierra support. Still few RWH preferences related UI work is needs to be reverse engineered and adapt.

You can download it from here: https://myjeeva.com/replywithheader

Also if you're using `v5.3` RWH, you could have got the beta update notification.

**Comment by funnel20** [comment]
@jeevatkm Thanks. Any idea when the Preferences will work?

**Comment by jeevatkm** [comment]
@funnel20 Still I haven't found a way to fix. It seems many other mail plugins have same preference cut issue.

I'm thinking of bringing RWH menu bar options as an alternate for preference options.

**Comment by jeevatkm** [comment]
Closing this moving towards #113 Thank you
