### ISSUE TITLE
Support for Thunderbird 60

### ISSUE THREAD

**Issue by deepers** [jeevatkm/ReplyWithHeader#114]
Hi,

I was testing out the Thunderbird 60.0 beta release, and I noticed that ReplyWithHeader is not compatible. Would you be able to provide support for Thunderbird 60?

Thanks,
Deepee

**Comment by jeevatkm** [comment]
@deepers Thanks for asking. You have created a ticket in wrong repo. RWH thunderbird repo is here https://github.com/jeevatkm/ReplyWithHeaderMozilla.

Surely RWH Mozilla would support 60 release. For now please refer to this thread jeevatkm/ReplyWithHeaderMozilla#61

I'm closing this one, please create an issue there https://github.com/jeevatkm/ReplyWithHeaderMozilla going forward. Thank you.

**Comment by deepers** [comment]
Sorry about that. Thanks,
Deepee

**Comment by jeevatkm** [comment]
@deepers no worries, yesterday I have updated v2.0-beta for TB 60.* here jeevatkm/ReplyWithHeaderMozilla#62 Thanks.
