### ISSUE TITLE
Locale Error

### ISSUE THREAD

**Issue by defrilitus** [jeevatkm/ReplyWithHeader#117]
This is indeed an excellent plug-in, but it contains a locale error.
In Apple Mail, when I choose the “English” date format in RWH (version 6.0), it comes out as “November 5, 2018 at 3:20:27 PM EST”. However, this is not English, but American (en-US).
All other major countries that employ English as a major language (e.g., UK, Ireland, Canada, Australia, New Zealand, South Africa) use the en-GB standard, thus “5 November 2018 15:20:27 -0500" or “5 Nov 2018 15:20:27 -0500".
Do you think that you can include the en-GB format in addition to the en-US one?
Thanks in advance!

PS:
In Thunderbird (RWH 1.5), where the extension is supposed to use the system settings, the date still uses the American format, even though my system locale is English - UK.

**Comment by jeevatkm** [comment]
@defrilitus Thanks for reporting an issue. 

RWH Mac plugin should work properly on Locale as its uses [Mac OS settings](https://github.com/jeevatkm/ReplyWithHeader/blob/master/ReplyWithHeader/MHHeaderString.m#L506-L507) unlike a RWH thunderbird plugin.

Screenshots for your references.
<img width="671" alt="screen shot 2018-11-18 at 1 13 13 am" src="https://user-images.githubusercontent.com/1175977/48670653-811b9b00-eacf-11e8-8d59-f84b2094b4a8.png">
<img width="672" alt="screen shot 2018-11-18 at 1 13 28 am" src="https://user-images.githubusercontent.com/1175977/48670656-8678e580-eacf-11e8-8bbc-77e4f336b566.png">


I will analysis it, if you could provide any further input on Mac plugin would be helpful.

**Comment by defrilitus** [comment]
@jeevatkm What you write above directly contradicts what is written on https://myjeeva.com/replywithheader, under Multilingual/Localization, where you state, with reference to the Apple plug-in, that "Header attribution in chosen language regardless of system locale/language. For e.g. system language is in Japanese & header attribution in English".
Also, why would you have a choice of locale within the plug-in if it used system settings? In any case, I can guarantee that RWH does not respect my system settings either for date or for time.

**Comment by jeevatkm** [comment]
@defrilitus Yes, this is "system language is in Japanese & header attribution in English" possible with RWH plugin. 

> why would you have a choice of locale within the plug-in if it used system settings?

Honestly I forgot the reason, date and time handling was implemented many years ago I believe its 2013 or 2014.

I will analyze the date and time issue, Thanks.

**Comment by jeevatkm** [comment]
@defrilitus Thanks for the ping. I have a plans to work on. However I'm unable to provide timeline. I'm occupied with my day work and other priorities.

**Comment by defrilitus** [comment]
@jeevatkm Thanks for the update.

**Comment by jeevatkm** [comment]
@defrilitus I have prepared `v6.1-beta` for Apple Mail, please try out and let me know. RWH should work as documented. Also added `en-GB` locale.

https://docs.myjeeva.com/rwh/ReplyWithHeader-v6.1-beta.zip

**Comment by defrilitus** [comment]
I've checked out the beta. "English" and "English (United States)" appear to be the same. With regard to "English (United Kingdom)", RWH gives me, for example, "Friday, 25 January 2019, 16:28". Outlook for Mac, on the other hand, gives me "Fri 25 Jan 2019 at 16:28". MacOS Mail gives me something very similar when using forward: "Fri 25 Jan 2019 at 16:28:25". If you could convert to either of the latter two, that would be great! Thanks for continuing your work on this add-on!

**Comment by jeevatkm** [comment]
@defrilitus I appreciate your efforts for trying out the beta version. 

I have left existing localization as-is for backward compatibility and added `en-US` and `en-GB`. The choice is left to users to choose.

Personally, I have only access to outlook.com and Office 2016/Office 365 at work on Windows. In that date format is -

```
// en-US
Sunday, February 10, 2019, 7:44 PM

So the date header format is -
EEEE, MMMM d, yyyy, h:mm a
```

With your issue report, I got an opportunity to address the date formatting issue which was unnoticed for a long.

Also, I have revised the RWH preferences on the date-

<img width="357" alt="screen shot 2019-02-10 at 10 08 00 pm" src="https://user-images.githubusercontent.com/1175977/52548243-55801800-2d81-11e9-894f-5e57871d3de9.png">

macOS mail behaviour is an inconsistency with the outlook windows version, RWH plugin tries to close the gap as much as possible. I think it's good enough to leave as-is after this fix.

**Comment by jeevatkm** [comment]
I'm closing this one 😄 Will be released as part of `RWH v6.1`.

**Comment by defrilitus** [comment]
Actually, I disagree with you. You state above that "Mac plugin should work properly on Locale as its uses Mac OS settings", but it doesn't. Absolutely not. Not quite sure why you state this, as it's obviously not the case.
You also say that there is an inconsistency between Outlook for Mac and Outlook for Windows. Again, this isn't correct. I run Outlook Pro Plus 2016 on a Windows 10 VM and it takes user date-formatting from the registry (accessed via Control Panel/Region). Outlook for MacOS does the same from System Preferences (user-accessible from System Preferences/Language and Region/Advanced/Dates). Neither Outlook for Windows nor Outlook for Mac oblige one to use a specific date format. By the way, the same is true of Apple Mail.
I'm a bit disappointed that RWH doesn't take into account user preferences, unlike its original raison d'être, which was to use macOS's locale settings.
However, if people find your plug-in to be useful, I am quite happy for both you and them.
Personally, I prefer the [QuoteFix](https://github.com/robertklep/quotefixformac/releases/) plug-in for Apple Mail, which—while it doesn't use user's locale preferences—at least gives users a free choice as to how the date is formatted.
In any case, thank you for taking the time to look at the issue. There's no right or wrong; it's purely subjective ;-)

**Comment by jeevatkm** [comment]
@defrilitus I think there is an understanding gap between us. I will try my best to describe it.

 First when you have reported the issue. I responded to my knowledge of memory. Then it turns to be partially incorrect after looking at the source code. As I mentioned above I took an opportunity to address the date format. In the past, I have received various issues/request (#104, #91, #88) around the date formatting. Till now RWH did not stick to any particular format/style. However, with `v6.1` release onwards RWH going to stick to one which is windows/outlook.com office format.

I would like to mention; I did not say which is right or wrong. Also, I'm not claiming which is right or wrong. 

---

I have described the behavior I saw (personally have access) with outlook.com and office 2016/365.  **For example, this is from outlook.com** 

<img width="691" alt="screen shot 2019-02-11 at 10 50 27 pm" src="https://user-images.githubusercontent.com/1175977/52617511-f558a700-2e50-11e9-9ace-2be9cb692082.png">

---

For example, the inconsistency within Apple Mail `Reply vs Forward` is -

**Reply**
<img width="532" alt="screen shot 2019-02-11 at 11 07 03 pm" src="https://user-images.githubusercontent.com/1175977/52617932-42894880-2e52-11e9-85ad-46e642d3b354.png">

**Forward**
<img width="683" alt="screen shot 2019-02-11 at 11 07 28 pm" src="https://user-images.githubusercontent.com/1175977/52617946-49b05680-2e52-11e9-81f1-637c8e86d167.png">

---

From my understanding, both Apple Mail and Office Outlook does not provide an option choose header date format. Or I'm not up-tp-date with facts.

**Comment by defrilitus** [comment]
To be honest, I wish that you would read my posts more carefully.
I did not write that Outlook for Windows gives an option to choose the date-header format. I wrote that Outlook takes the date-header format from the Registry. Users can access these options via the Control Panel. Thus, Outlook will use the system language to set the header language and the Region long date/short time to set the header.
A similar thing happens in macOS: change the system language and/or date/time format in System Preferences, and Apple Mail and Outlook for Mac will change the format of their headers accordingly.
Please try these options out. They will give you a better understanding as to how most mail clients apply default reply formats.

**Comment by jeevatkm** [comment]
@defrilitus Thanks, surely I have read your message then only I have responded to it with the background, previous issues references, screenshots. 

Yes, I have also tried your suggestion yesterday for Apple Mail, it did not honor the system settings for me (_Please note: while testing this RWH plugin was uninstalled on macbook pro_) I don't know why. You could see that differences (Reply vs Forward) on the provided screenshot on previous message.
