### ISSUE TITLE
reply with header disabled for mac mail 12

### ISSUE THREAD

**Issue by ghost** [jeevatkm/ReplyWithHeader#120]
[ReplyWithHeaderFault.docx](https://github.com/jeevatkm/ReplyWithHeader/files/2609428/ReplyWithHeaderFault.docx)

**Comment by anjikn** [comment]
Reply With Header doesn't seem to work with Mai V12. Is there a fix for this?

**Comment by PSC-1** [comment]
The Installer doesn't seem to access the folders correctly.
You can do this manually to make it work.

- Close Mail.
- In Finder, press Command+Shift+G
- In the pop-up box, Enter: **/Users/_[YOUR NAME]_/Library/Mail/Bundles**
- Delete the existing **ReplyWithHeader.mailbundle**
- Copy the new one from the recent v6.0 downloaded unzipped folder to that folder.
- Start Mail.
- Go to "Mail > Preferences > General"
- Click "Manage Plug-ins" button
- Check mark the "ReplyWithHeader.mailbundle"
- Click "Apply and Restart Mail.app" button

Should work for you now. Did for me :)

**Comment by jeevatkm** [comment]
I'm closing this one.
