### ISSUE TITLE
Reply with header for macOS Mojave 10.14.3 disabled

### ISSUE THREAD

**Issue by jorgeberman** [jeevatkm/ReplyWithHeader#121]
[Jorge Mail Log.zip](https://github.com/jeevatkm/ReplyWithHeader/files/2846283/Jorge.Mail.Log.zip)

**Comment by jeevatkm** [comment]
@jorgeberman I had a look at the provided log file. It does not contain any error related to RWH.

Typically, whenever macOS update has been released, `Mail.app` plugin compatible ID gets changed. So the user has to re-run the installer then installer to use RWH again.

Could you please let me know, what you have tried and steps you have followed so far?

**Comment by jorgeberman** [comment]
Thank you for your answer.

With Mail.app closed, I’ve ran Uninstall.command and then Install-or-Upgrade-or-Reenable.command but RWH does not appear . . .

Jorge N. Berman
jorge@berman.com.ar <mailto:jorge@berman.com.ar>
15 5487-3377

**Comment by jeevatkm** [comment]
@jorgeberman RWH installation instructions/guide is in file `Install-Instructions-Mojave-OS-and-Above.txt`, please have a look.

Seem like you have successfully finished the steps until execution of `Install-or-Upgrade-or-Reenable.command`.

So, continue the installation instructions from the file.

**Comment by jeevatkm** [comment]
@jorgeberman Any updates? FYI,  RWH v6.1 released.

**Comment by jorgeberman** [comment]
Thank you very much!

What I did was to manually erase v6 folder and the reinstalled: finally worked. With v6.1 works perfectly.

Jorge N. Berman
jorge@berman.com.ar <mailto:jorge@berman.com.ar>
15 5487-3377

**Comment by tobikster** [comment]
I also have a problem with using this plugin on MacOS Mojave 10.14.3 and mail.app 12.2. When I tried to enable the plugin and restart mail app, I got an error saying this plugin is incompatible (please refer the screenshot)
<img width="488" alt="screenshot 2019-03-04 at 12 57 44" src="https://user-images.githubusercontent.com/1465627/53732118-2d19a400-3e7d-11e9-81e9-3a6c51523e5d.png">

**Comment by jeevatkm** [comment]
@tobikster Its seems like a permission issue. Could you please manually delete the `~/Library/Mail/Bundles/ReplyWithHeader.mailbundle` and install it again?

I have not yet found the best way to solve this problem.

**Comment by networkjitter** [comment]
Same problem here, mail is disabling the plug-in.
<img width="780" alt="Screen Shot 2019-03-13 at 10 08 06 AM" src="https://user-images.githubusercontent.com/7738924/54300403-07c21f80-457a-11e9-810d-d2ef8246ec81.png">
```
RWH:: Starting installation...
RWH:: Mail Plugin - ReplyWithHeader
RWH:: Mac OS X version: 10.14.3
RWH:: Mail.app 12.2 [Build 3445.102.3]
RWH:: user 'myusername' is installing plugin
RWH:: Enabling plugin support in Mail.app
RWH:: Domain is /Users/myusername/Library/Containers/com.apple.mail/Data/Library/Preferences/com.apple.mail.plist
RWH:: Adding UUID A4343FAF-AE18-40D0-8A16-DFAE481AF9C1
2019-03-13 10:18:09.191 defaults[13914:1148948] Could not write domain /Users/myusername/Downloads/ReplyWithHeader-v6.1/ReplyWithHeader.mailbundle/Contents/Info.plist; exiting

RWH:: Installing ReplyWithHeader Mail plugin
cp: /Users/myusername/Downloads/ReplyWithHeader-v6.1/ReplyWithHeader.mailbundle: unable to copy extended attributes to /Users/myusername/Library/Mail/Bundles/ReplyWithHeader.mailbundle: Permission denied
cp: /Users/myusername/Downloads/ReplyWithHeader-v6.1/ReplyWithHeader.mailbundle: Permission denied
RWH:: Installation complete

RWH:: Plugin copied into '/Users/myusername/Library/Mail/Bundles'. Follow the "Step 3" from "Install-Instructions-Mojave-OS-and-Above.txt"


logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```
<img width="532" alt="Screen Shot 2019-03-13 at 9 58 57 AM" src="https://user-images.githubusercontent.com/7738924/54300450-1e687680-457a-11e9-9e31-927778755821.png">

**Comment by networkjitter** [comment]
Looking at the other issue threads, it seems the UUID part is important, so I decided to work on fixing that part. I re-extracted the RWH archive and then used iTerm instead of terminal, now that issue seems to be clear, but mail is still disabling the plug-in at startup.

```
$ ./Install-or-Upgrade-or-Reenable.command

RWH:: Starting installation...
RWH:: Mail Plugin - ReplyWithHeader
RWH:: Mac OS X version: 10.14.3
RWH:: Mail.app 12.2 [Build 3445.102.3]
RWH:: user 'myusername' is installing plugin
RWH:: Enabling plugin support in Mail.app
RWH:: Domain is /Users/myusername/Library/Containers/com.apple.mail/Data/Library/Preferences/com.apple.mail.plist
RWH:: Adding UUID A4343FAF-AE18-40D0-8A16-DFAE481AF9C1

RWH:: Installing ReplyWithHeader Mail plugin
RWH:: Installation complete

RWH:: Plugin copied into '/Users/myusername/Library/Mail/Bundles'. Follow the "Step 3" from "Install-Instructions-Mojave-OS-and-Above.txt"
```
Cheers

**Comment by tobikster** [comment]
@jeevatkm I tried to remove this file as well as download RWH and install again - still the same result.

**Comment by networkjitter** [comment]
@jeevatkm Any thoughts as to why Mail.app 12.2 is disabling the plug-in? I am happy to help troubleshoot if needed.

I'm really hoping to regain RWH functionality.  Thank you.

**Comment by networkjitter** [comment]
FWIW - Still broken with Mail.app v12.4 following the Mojave update
<img width="532" alt="Screen Shot 2019-04-02 at 12 24 42 PM" src="https://user-images.githubusercontent.com/7738924/55430216-5ee85e00-5542-11e9-9272-3a235fd9615f.png">

**Comment by jeevatkm** [comment]
@networkjitter Thanks for the update. 

Today I have updated my MacBook Pro to macOS 10.14.4. The strange or important thing is I did not reinstall the RWH plugin. Instead -

* After macOS install
* I opened up Mail.app went to Preferences -> Tab General -> Manage Plug-ins
* Enabled RWH plugin again from the list by clicking checkbox -> click `Apply and Restart Mail`
* Mail.app restarted and RWH plugin is working again

So not sure above steps/behavior applicable to everyone. If it is then Its good and I have to update the install instruction accordingly 😄

If any user could validate the above scenario could be very useful.

**Comment by networkjitter** [comment]
@jeevatkm 

I believe the steps you provided are already covered by the Mojave install instructions.

I was thinking there may be something wrong with my particular macOS Mojave installation, so I decided to install and test v6.1 on another MacBook that is running High Sierra (10.13.6). I am not able to get it working on High Sierra either. The installation script seems to work fine and I don't get any errors on mail.app startup, but there is no RWH tab in Preferences.

Any thoughts?  I have been using this plug-in for almost 5 years now without any issues until now.

**Comment by jeevatkm** [comment]
@networkjitter I know that is available in Mojave install instructions. But after my MacBook Pro OS update to 10.14.4; I have only performed Step 3 from [instructions file](https://github.com/jeevatkm/ReplyWithHeader/blob/master/Misc/Install-Instructions-Mojave-OS-and-Above.txt)

No reinstall of RWH after OS update. That's why I would like to confirm steps.

Things got complicated due to new security changes in Mojave OS. I would really like to address this once for all, I'm sorry; trying my best to find a way.

**Comment by networkjitter** [comment]
@jeevatkm - Got it, you are looking for verification of steps for re-enablement after minor version upgrades of Mojave (e.g. 10.14.3 -> 10.14.4).

Any thoughts on why I'm having issues with 6.1 on High Sierra?

Thank you for all your efforts, they are much appreciated!

**Comment by jeevatkm** [comment]
@networkjitter Since `v6.0` RWH release onwards, there is no RWH tab in the Mail preferences. It got moved to Mail.app main menu. You would see the RWH menu in the menu bar.  Could you check it?

**Comment by networkjitter** [comment]
@jeevatkm Yes, the RWH menu is there and of course the plug-in is working just fine in High Sierra. ;) Thank you for educating me.

WRT to Mojave, is there anything that I can do to pinpoint the issue with my installation? I am considering upgrading the High Sierra machine to Mojave to see if I run into the same issue or perhaps testing with a new user account on my main Mojave machine where RWH is currently non-functional.

**Comment by jeevatkm** [comment]
@networkjitter Please give it try on your new machine and share your experience.

**Comment by networkjitter** [comment]
@jeevatkm - I tested with a new user login on my Mojave machine and RWH worked as expected. Sounds like I may need to manually blow away my "V6" folder and start fresh. Anyone know how to do this in the least invasive manner? (i.e. preserve mail rules, smart mailboxes, etc.)

**Comment by networkjitter** [comment]
Deleting the entire `~/Library/mail` folder and restarting mail did not fix the issue, however I finally had success enabling RWH after removing the following two folders.

```
~/Library/Containers/com.apple.mail
~/Library/Containers/com.apple.MailServiceAgent
```

This article is what clued me into trying this: 
https://appletoolbox.com/2018/09/mail-not-working-after-macos-mojave-upgrade-how-to-fix/#Mail_Crashing_or_Slow_After_macOS_Mojave_Upgrade_How-To_Fix

**Comment by jeevatkm** [comment]
@networkjitter I'm glad to hear you have sorted the issue on your machine. Thank you for sharing your experience.

**Comment by jeevatkm** [comment]
@jorgeberman @networkjitter Shall I close this issue?

**Comment by jorgeberman** [comment]
Yes please

**Comment by networkjitter** [comment]
All good here, thanks!

**Comment by jorgeberman** [comment]
Thanks to you!

> De: networkjitter
> Enviado: lunes, 2 de septiembre de 2019 6:09 p. m.
> Para: jeevatkm/ReplyWithHeader
> Cc: jorgeberman; Mention
> Asunto: Re: [jeevatkm/ReplyWithHeader] Reply with header for macOS Mojave 10.14.3 disabled (#121)
> 
> 
> All good here, thanks!
>

**Comment by jeevatkm** [comment]
Thank you @jorgeberman, @networkjitter.

Just wondering, shall I take help from you for macOS Catalina support testing?  Will ping you whenever I have the beta version of RWH.

**Comment by jorgeberman** [comment]
I’ll try . . . if it will not too difficult. . .

Jorge N. Berman
Enviado desde mi iPhone

**Comment by jorgeberman** [comment]
Hi,

It looks that ReplyWithHeader-v6.1 doesn’t work with macOS Catalina . . . isn’t it?

Regards,

Jorge N. Berman
jorge@berman.com.ar <mailto:jorge@berman.com.ar>
15 5487-3377
