### ISSUE TITLE
Date format has local system format and not the one of the selected language

### ISSUE THREAD

**Issue by ghost** [jeevatkm/ReplyWithHeader#37]
Related to 4.2beta:
The date headers are always formatted in the local system format regardless which language setting one has chosen in the plugin. Because of that one has mixed language wording in the date string.

Example (note the german output of the sent date in the english context):

**From:** Mini Minimizer [mailto:mini@minimizer.com] 
**Sent:** Montag, 05. August 2013 11:13:37 MESZ
**To:** 'Max Maximizer'
**Subject:** Some subject text coming here

should be 
**From:** Mini Minimizer [mailto:mini@minimizer.com] 
**Sent:** Monday, August 05, 2013 11:13
**To:** Max Maximizer
**Subject:** Some subject text coming here

Better would be if the date format is follwing the selected language. The suffix *MESZ* is also a bit confusing.
The display of seconds is fine for me even if Outlook has not such detailed output.

**Comment by jeevatkm** [comment]
Addressed, part of next release.
