### ISSUE TITLE
Unreadable chars in header

### ISSUE THREAD

**Issue by insekt** [jeevatkm/ReplyWithHeader#73]
Sometimes I see unreadable chars instead of name.
![2014-10-13 14-07-33 re](https://cloud.githubusercontent.com/assets/6427964/4611968/0ca86e38-52c1-11e4-8e77-2c5cbada75a9.png)

**Comment by jeevatkm** [comment]
@insekt I have addressed this issue, is it possible to try beta version and share your feedback?

Kindly let me know!

**Comment by insekt** [comment]
No problem.
Where can I get beta version?

**Comment by jeevatkm** [comment]
Thanks, here it is [https://app.box.com/s/n6dzs9s3ucpsf7zyqraeiohujmnfwest](https://app.box.com/s/n6dzs9s3ucpsf7zyqraeiohujmnfwest).

**Comment by insekt** [comment]
Works fine!
Here is a screenshot of header from the same letter
![2015-03-09 19-56-35 re](https://cloud.githubusercontent.com/assets/6427964/6559846/ccefbf2c-c696-11e4-966d-16e391e3391d.png)

**Comment by jeevatkm** [comment]
Thanks @insekt for testing, I'm doing few more improvements. Coming weekend I will release it.
