### ISSUE TITLE
"From Header Attribution Style" issue

### ISSUE THREAD

**Issue by dicksonnathan** [jeevatkm/ReplyWithHeader#79]
After upgrading to version 4.9, selecting either Default or Extended "From header attribution style" always displays "From: Name email-address"

I'm using Mail 8.2 (2070.6) on Yosemite (10.10.2)

I've downgraded to 4.8 and the settings are back normal.

**Comment by jeevatkm** [comment]
Thanks for notifying, will check and let you know!

**Comment by jeevatkm** [comment]
Can you please try this build and share your feedback?
https://app.box.com/s/ky716t9czwmdcl0pbx8b5yfrbeiss05k

**Comment by dicksonnathan** [comment]
This build works fine. Both Default and Extended "From Header Attribution Style" works as intended. Thanks for the quick response and fix!
