### ISSUE TITLE
Can't resize the Mail.app's Preferences window when focus is on the Accounts tab

### ISSUE THREAD

**Issue by tvnshack** [jeevatkm/ReplyWithHeader#80]
Hello,

Since I've installed that plugin, the Mail Preference window can't be resized anymore. I mean, the "Accounts" tab. How strange !  I need to resize this window always because I can't identify my (many) mail accounts when I want to activate them depending on my network setting. Even if the the "grab" icons show up near the window's edge, the window won't follow. Is your plug-in interfering with the size of the Prefs' window ... constantly, even of the RWH tab hasn't the focus ?

**Comment by jeevatkm** [comment]
I have verified it, on click of every menu item in the prefs window. It adjust the size of the window **to make every icon visible in the prefs window**. Sorry for the inconvenience.

**Comment by tvnshack** [comment]
Hello,

Unfortunately not here !  The mouse icon changes to an arrow when hovering over the edges of the prefs window .. but nothing happen when actually clicking to drag the edges and resize window.

Mail  Version 7.3 (1878.6)

MacOSX 10.9.5

Have you tried with these versions ?

Thanks
Thierry

**Comment by jeevatkm** [comment]
Yes, I will try to sort out this in best possible manner for upcoming version.

**Comment by jeevatkm** [comment]
Issue addressed, Not only Accounts tab. Taken care for Rules and Signatures too!

Will be released in v5.0

**Comment by tvnshack** [comment]
Awesome !!!

**Comment by jeevatkm** [comment]
Can you please try v5.0-beta and share your feedback?
Download Link: [https://app.box.com/s/qta2i4osh2lz9f2jojjg1j98fd762sdo](https://app.box.com/s/qta2i4osh2lz9f2jojjg1j98fd762sdo)

**Comment by tvnshack** [comment]
Excellent .... will do right away ...

**Comment by tvnshack** [comment]
Wonderful !  Prefs window sizing problem fixed.

Now, perhaps you could work on this bug (
https://github.com/jeevatkm/ReplyWithHeader/issues/81).

Steps to reproduce it:

 - Open Mail and in the Viewer, select a snippet of text in a mail you've
received (this one for example)

 - With that selection active, click Reply.  The new mail composer window
proposed the text snippet adorned with the details of the selected mail
header. Fine.

 - With that same text selection active, click Forward. Here is the bug :
In the new mail composer window, only the snippet of text is copied. No
header information are composed.

Thanks a lot,
Thierry

**Comment by jeevatkm** [comment]
@tvnshack - Thanks for your time and confirmation.

Let's continue our conversation in that thread.
