### ISSUE TITLE
Outlook-style Reply All behavior (preserve To and CC recipients)

### ISSUE THREAD

**Issue by modest** [jeevatkm/ReplyWithHeader#82]
Enhancement request :)
The most annoying behavior in Apple Mail is Reply All.  Unlike Outlook, it does not preserve the To/CC line of the message you are replying to.  Instead, it moves everyone except the last sender to the CC line.

# Example

#### Received message

> **From:** Alice
> **To:** Bob, Cathy, David, YOU
> **CC:** Eric, Frank

## Outlook Reply-All behavior

> **From:** YOU
> **To:** Alice, Bob, Cathy, David
> **CC:** Eric, Frank

## Apple Mail Reply-All behavior

> **From:** YOU
> **To:** Alice
> **CC:** Bob, Cathy, David, Eric, Frank

All of the recipients on the To line have been dropped to CC.

**Comment by jeevatkm** [comment]
Before committing to this behaviour, I will have to verify few internal elements in Mail.app.

Will let you know, currently I labeled as `analyze`.

**Comment by jeevatkm** [comment]
Poor internal API support Mail app, however I'm planing to handle via workaround and logic.

Are you interest in try out pre-release version and share your feedback?

**Comment by jeevatkm** [comment]
It's done!

**Comment by modest** [comment]
Awesome! Thank you! I will test this out in the next release. Let me know if you want any feedback. :)

**Comment by jeevatkm** [comment]
Can you please try v5.0-beta and share your feedback?
Download Link: [https://app.box.com/s/qta2i4osh2lz9f2jojjg1j98fd762sdo](https://app.box.com/s/qta2i4osh2lz9f2jojjg1j98fd762sdo)

**Comment by jeevatkm** [comment]
@modest - Did you get a chance to verify the implementation?

**Comment by modest** [comment]
@jeevatkm The behavior is *perfect*.  I tested all the cases I could find, and they all behaved exactly as expected with Outlook parity.  Thank you!

**Comment by jeevatkm** [comment]
@modest I'm glad it worked as expected :)
