### ISSUE TITLE
ReplyWithHeader being disabled due to locale issue

### ISSUE THREAD

**Issue by svandi** [jeevatkm/ReplyWithHeader#83]
I'm running OS X 10.9.5 with Mail v. 7.3.

I've been running this successfully with Mavericks as well as earlier OS versions.  Not sure of the change event, but I see that the plugin is being disabled on the startup of Mail.  Here is the log data:

<pre>5/12/15 5:40:01.636 PM Mail[12876]: ReplyWithHeader v4.9 plugin loaded, OS X version: 10.9
5/12/15 5:40:01.636 PM Mail[12876]: MailHeader.m: 168 Localized String locale: English key: PLUGIN_NAME value: (null)
5/12/15 5:40:01.636 PM Mail[12876]: MailHeader.m: 172 Localized String locale: en key: PLUGIN_NAME value: ReplyWithHeader
5/12/15 5:40:01.637 PM Mail[12876]: ReplyWithHeader v4.9 debug log enabled: YES
5/12/15 5:40:01.637 PM Mail[12876]: MailHeader.m: 80 Supported Localization (
    de,
    en,
    es,
    fr,
    it,
    ja,
    ko,
    nb,
    nl,
    "pt-PT",
    pt,
    ru,
    sv,
    uk,
    "zh-Hans",
    "zh-Hant"
)
5/12/15 5:40:01.637 PM Mail[12876]: MailHeader.m: 168 Localized String locale: English key: PLUGIN_NAME value: (null)
5/12/15 5:40:01.637 PM Mail[12876]: MailHeader.m: 172 Localized String locale: en key: PLUGIN_NAME value: ReplyWithHeader
5/12/15 5:40:01.638 PM Mail[12876]: MailHeader.m: 84 ReplyWithHeader v4.9 - Is locale supported: NO
5/12/15 5:40:01.638 PM Mail[12876]: MailHeader.m: 168 Localized String locale: English key: PLUGIN_NAME value: (null)
5/12/15 5:40:01.639 PM Mail[12876]: MailHeader.m: 172 Localized String locale: en key: PLUGIN_NAME value: ReplyWithHeader
5/12/15 5:40:01.639 PM Mail[12876]: WARNING :: ReplyWithHeader v4.9 is currently not supported in your Locale[ (null)(English) ] it may not work as expected, so disabling it.
Please contact plugin author for support (http://myjeeva.com/replywithheader).
5/12/15 5:40:01.639 PM Mail[12876]: MailHeader.m: 168 Localized String locale: English key: PLUGIN_NAME value: (null)
5/12/15 5:40:01.640 PM Mail[12876]: MailHeader.m: 172 Localized String locale: en key: PLUGIN_NAME value: ReplyWithHeader
5/12/15 5:40:01.640 PM Mail[12876]: ReplyWithHeader plugin is disabled in mail preferences
5/12/15 5:40:02.967 PM Mail[12876]: Could not create query for expression ((null)) && (kMDItemContentType == 'com.apple.mail.emlx')
5/12/15 5:40:02.998 PM WindowServer[133]: disable_update_timeout: UI updates were forcibly disabled by application "Mail" for over 1.00 seconds. Server has re-enabled them.
5/12/15 5:40:05.647 PM WindowServer[133]: common_reenable_update: UI updates were finally reenabled by application "Mail" after 3.65 seconds (server forcibly re-enabled them after 1.00 seconds)
5/12/15 5:40:08.337 PM Mail[12876]: *** -[IADomainCache init]: IA domains cache couldn't be read.
5/12/15 5:40:08.337 PM Mail[12876]: -[IAPluginManager allAListPlugins] [546] -- *** warning: we're on the slow path.</pre>

**Comment by jeevatkm** [comment]
Any region/locale settings change happened recently in your machine? RWH is detecting english but some addition value comes too.

I see in the log like this:
<pre>5/12/15 5:40:01.639 PM Mail[12876]: WARNING :: ReplyWithHeader v4.9 is currently not supported in your Locale[ (null)(English) ] it may not work as expected, so disabling it.
Please contact plugin author for support (http://myjeeva.com/replywithheader).</pre>

Will verify at my end too.

**Comment by svandi** [comment]
The plugin is working now, but I'm not sure of the root cause.  I have not made any region/locale setting changes, but while looking for these, I noticed the "Enable" checkbox in the Mail.app preference pane for RWH was not selected.  This is not really surprising since the log shows it being disabled during startup.  Nevertheless when I checked the box to enable it, the plugin works as expected.  After a restart of Mail.app, the plugin is still working and enabled.  The log now reads:
=========
5/14/15 4:11:19.531 PM Mail[16803]: ReplyWithHeader v4.9 plugin loaded, OS X version: 10.9
5/14/15 4:11:19.532 PM Mail[16803]: MailHeader.m: 172 Localized String locale: en key: PLUGIN_NAME value: ReplyWithHeader
5/14/15 4:11:19.533 PM Mail[16803]: ReplyWithHeader v4.9 debug log enabled: YES
5/14/15 4:11:19.533 PM Mail[16803]: MailHeader.m: 80 Supported Localization (
    de,
    en,
    es,
    fr,
    it,
    ja,
    ko,
    nb,
    nl,
    "pt-PT",
    pt,
    ru,
    sv,
    uk,
    "zh-Hans",
    "zh-Hant"
)
5/14/15 4:11:19.534 PM Mail[16803]: MailHeader.m: 172 Localized String locale: en key: PLUGIN_NAME value: ReplyWithHeader
5/14/15 4:11:19.534 PM Mail[16803]: MailHeader.m: 84 ReplyWithHeader v4.9 - Is locale supported: YES
==============
I disabled the plugin through the preference pane and restarted Mail.app.  The original locale message no longer reproduces.  When disabled, the log looks normal:

===============
5/14/15 4:26:32.580 PM Mail[16866]: ReplyWithHeader v4.9 plugin loaded, OS X version: 10.9
5/14/15 4:26:32.581 PM Mail[16866]: MailHeader.m: 172 Localized String locale: en key: PLUGIN_NAME value: ReplyWithHeader
5/14/15 4:26:32.582 PM Mail[16866]: ReplyWithHeader v4.9 debug log enabled: YES
5/14/15 4:26:32.585 PM Mail[16866]: MailHeader.m: 80 Supported Localization (
    de,
    en,
    es,
    fr,
    it,
    ja,
    ko,
    nb,
    nl,
    "pt-PT",
    pt,
    ru,
    sv,
    uk,
    "zh-Hans",
    "zh-Hant"
)
5/14/15 4:26:32.586 PM Mail[16866]: MailHeader.m: 172 Localized String locale: en key: PLUGIN_NAME value: ReplyWithHeader
5/14/15 4:26:32.586 PM Mail[16866]: MailHeader.m: 84 ReplyWithHeader v4.9 - Is locale supported: YES
5/14/15 4:26:32.587 PM Mail[16866]: MailHeader.m: 172 Localized String locale: en key: PLUGIN_NAME value: ReplyWithHeader
5/14/15 4:26:32.587 PM Mail[16866]: ReplyWithHeader plugin is disabled in mail preferences
=======================
I'm not sure if checking the Enable box in Preferences reset some corrupted preference data or what.  I did have a hard disk failure a few weeks ago and restored from a Time Machine backup.  Possibly the backup I restored from had some preference corruption?  At any rate, I'm happy it is working now!

**Comment by jeevatkm** [comment]
I'm glad to hear :) please let me know if your come across any issue.
