### ISSUE TITLE
Add ability to reply with full, raw headers

### ISSUE THREAD

**Issue by fmaxwell** [jeevatkm/ReplyWithHeader#85]
Feature request:  Add the ability to reply with the full, raw headers, including "Received:" headers with IP addresses.  That's what I was looking for when I found the ReplyWithHeader plugin.  

Replying with the full, raw headers is a necessary feature for people who report spammers, phishing attacks, criminal scams (Nigerian 419, craigslist vehicle pay-with-Western-Union, etc.), and malware payloads and links sent by email.  These headers are needed by network abuse departments and law enforcement agencies for their investigations.

**Comment by jeevatkm** [comment]
I have scheduled it for coming release.

**Comment by fmaxwell** [comment]
That's fantastic.  Thank you very much.

**Comment by jeevatkm** [comment]
Can you please try v5.0-beta and share your feedback?
Download Link: [https://app.box.com/s/qta2i4osh2lz9f2jojjg1j98fd762sdo](https://app.box.com/s/qta2i4osh2lz9f2jojjg1j98fd762sdo)

**Comment by fmaxwell** [comment]
The installation/upgrade went without a problem.

I wish I had better news to report on the testing, but as soon as I check the "Include all headers" box, I can no longer reply, reply-all, or forward.  The buttons visually indicate being pressed, but nothing happens.  I tried with various combinations of other from, to & CC, and header quoting sequence and labels, including all on default.  I was unable to get a response to reply, reply-all, or forward buttons.

It did not 

matter if the buttons were pressed on the main mail screen or on an individual message windows brought up by double-clicking a message.

I am running:



Please let me know if there is any additional information or testing you need and I will make it a priority.

**Comment by jeevatkm** [comment]
Can you please enable RWH debug using below command and restart the Mail.app?
<pre><code>defaults write com.apple.mail MHDebugLog -bool true</code></pre>

Now watch Console.app for any errors from Mail.app.

**Comment by jeevatkm** [comment]
Certain message headers were causing an issue in Yosemite. I have applied the fix. Can you please download updated beta version here ([https://app.box.com/s/qta2i4osh2lz9f2jojjg1j98fd762sdo](https://app.box.com/s/qta2i4osh2lz9f2jojjg1j98fd762sdo))

Kindly let me know the outcome!

**Comment by fmaxwell** [comment]
Sorry for the delay in replying.  With the box unchecked, it looks good.  With it checked, pressing the Reply button results in:

5/29/15 2:05:00.170 AM Mail[2837]: *** Assertion failure in -[MCMessageHeaders headersForKey:], /SourceCache/Mail/Mail-2100/MailCore/Message/MCMessageHeaders.m:735
5/29/15 2:05:00.171 AM Mail[2837]: Use -messageIDListForKey: for message ID header keys
5/29/15 2:05:00.172 AM Mail[2837]: (
	0   CoreFoundation                      0x00007fff9282e03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff971f376e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff9282de1a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff90cf88cb -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   MailCore                            0x00007fff9260177d -[MCMessageHeaders headersForKey:] + 350
	5   ReplyWithHeader                     0x0000000116772854 ReplyWithHeader + 10324
	6   ReplyWithHeader                     0x0000000116776a7a ReplyWithHeader + 27258
	7   Mail                                0x000000010fffc948 Mail + 514376
	8   Mail                                0x000000010fffc2f2 Mail + 512754
	9   Mail                                0x000000010fff9452 Mail + 500818
	10  CoreFoundation                      0x00007fff927057bc __invoking___ + 140
	11  CoreFoundation                      0x00007fff92705612 -[NSInvocation invoke] + 290
	12  MailCore                            0x00007fff92656a14 -[MCThrowingInvocationOperation main] + 48
	13  MailCore                            0x00007fff925e815e -[MCMainThreadInvocationOperation main] + 55
	14  Foundation                          0x00007fff90cc2d00 __NSThreadPerformPerform + 293
	15  CoreFoundation                      0x00007fff9274aa01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	16  CoreFoundation                      0x00007fff9273cb8d __CFRunLoopDoSources0 + 269
	17  CoreFoundation                      0x00007fff9273c1bf __CFRunLoopRun + 927
	18  CoreFoundation                      0x00007fff9273bbd8 CFRunLoopRunSpecific + 296
	19  HIToolbox                           0x00007fff986ef56f RunCurrentEventLoopInMode + 235
	20  HIToolbox                           0x00007fff986ef2ea ReceiveNextEventCommon + 431
	21  HIToolbox                           0x00007fff986ef12b _BlockUntilNextEventMatchingListInModeWithFilter + 71
	22  AppKit                              0x00007fff8b4dc98b _DPSNextEvent + 978
	23  AppKit                              0x00007fff8b4dbf38 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
	24  AppKit                              0x00007fff8b4d1bd3 -[NSApplication run] + 594
	25  AppKit                              0x00007fff8b44e324 NSApplicationMain + 1832
	26  libdyld.dylib                       0x00007fff8c0445c9 start + 1
	27  ???                                 0x0000000000000001 0x0 + 1
)

**Comment by fmaxwell** [comment]
Hi.  Sorry to report that it is still not working.  But the console contains a much more lengthy set of messages now when the Reply button is pressed:

5/29/15 2:12:04.431 AM Mail[3610]: MHHeadersEditor.m: 87 msgComposeType: 1
5/29/15 2:12:04.504 AM Mail[3610]: MHHeadersEditor.m: 87 msgComposeType: 1
5/29/15 2:12:04.512 AM Mail[3610]: MHMailMessage.m: 49 Message compose type is 1
5/29/15 2:12:04.512 AM Mail[3610]: MHQuotedMailOriginal.m: 158 Mail Document: <EditableWebMessageDocument: 0x600000323160>
5/29/15 2:12:04.512 AM Mail[3610]: MHQuotedMailOriginal.m: 159 Composing message type is 1
5/29/15 2:12:04.512 AM Mail[3610]: MHQuotedMailOriginal.m: 160 Complete HTML string <br><div class="AppleOriginalContents" style="direction: ltr;"><blockquote type="cite"><div>On May 29, 2015, at 2:02 AM, Jeevanandam M. &lt;notifications@github.com&gt; wrote:</div><br class="Apple-interchange-newline"><div><p class="">Certain message headers were causing an issue in Yosemite. I have applied the fix. Can you please download updated beta version here (<a href="https://app.box.com/s/qta2i4osh2lz9f2jojjg1j98fd762sdo" class="">https://app.box.com/s/qta2i4osh2lz9f2jojjg1j98fd762sdo</a>)</p><p class="">Kindly let me know the outcome!</p><p style="font-size:small;-webkit-text-size-adjust:none;color:#666;" class="">—<br class="">Reply to this email directly or <a href="https://github.com/jeevatkm/ReplyWithHeader/issues/85#issuecomment-106700077" class="">view it on GitHub</a>.<img alt="" height="1" src="https://github.com/notifications/beacon/AL6W8msaPzK9FhQoTKqwhzv-RfE5WXUSks5oN_iPgaJpZM4EeXDp.gif" width="1" class=""></p>
<div itemscope="" itemtype="http://schema.org/EmailMessage" class="">
  <div itemprop="action" itemscope="" itemtype="http://schema.org/ViewAction" class="">
    <link itemprop="url" href="https://github.com/jeevatkm/ReplyWithHeader/issues/85#issuecomment-106700077" class="">
    <meta itemprop="name" content="View Issue" class="">
  </div>
  <meta itemprop="description" content="View this Issue on GitHub" class="">
</div>
</div></blockquote></div><br>
5/29/15 2:12:04.513 AM Mail[3610]: MHQuotedMailOriginal.m: 214 Composing mail isHTMLMail YES
5/29/15 2:12:04.513 AM Mail[3610]: MHQuotedMailOriginal.m: 220 initVars Header border text: <hr style='border:none;border-top:solid #B5C4DF 1.0pt;padding:0 0 0 0;margin:10px 0 5px 0;' />
5/29/15 2:12:04.513 AM Mail[3610]: MHQuotedMailOriginal.m: 176 isBlockquotePresent = YES
5/29/15 2:12:04.513 AM Mail[3610]: MHQuotedMailOriginal.m: 386 No of child nodes: 1
5/29/15 2:12:04.513 AM Mail[3610]: MHQuotedMailOriginal.m: 391 getBlockquoteTagNode:: BLOCKQUOTE Node found at 0
5/29/15 2:12:04.513 AM Mail[3610]: MHQuotedMailOriginal.m: 315 Handling remaining locale by Regex
5/29/15 2:12:04.513 AM Mail[3610]: MHQuotedMailOriginal.m: 325 Before while loop, Text range is {76, 2}
5/29/15 2:12:04.514 AM Mail[3610]: MHQuotedMailOriginal.m: 343 Node name: DIV, Node Type: 1, Node Value: On May 29, 2015, at 2:02 AM, Jeevanandam M. <notifications@github.com> wrote:
5/29/15 2:12:04.514 AM Mail[3610]: MHHeaderString.m: 188 From User defaults choosenLocaleIdentifier en
5/29/15 2:12:04.515 AM Mail[3610]: MHHeaderString.m: 225 Before cleanup allHeaderKeys:: (
    received,
    date,
    "dkim-signature",
    from,
    "reply-to",
    to,
    cc,
    "message-id",
    "in-reply-to",
    references,
    subject,
    "mime-version",
    "content-type",
    "content-transfer-encoding",
    precedence,
    "x-github-sender",
    "x-github-recipient",
    "x-github-reason",
    "list-id",
    "list-archive",
    "list-post",
    "list-unsubscribe",
    "x-auto-response-suppress",
    "x-github-recipient-address",
    "x-rcpt-to",
    "return-path"
)
5/29/15 2:12:04.515 AM Mail[3610]: MHHeaderString.m: 243 Key: reply-to, Values: jeevatkm/ReplyWithHeader <reply@reply.github.com>
5/29/15 2:12:04.516 AM Mail[3610]: MHHeaderString.m: 248 After cleanup allHeaderKeys:: (
    received,
    "dkim-signature",
    "message-id",
    "in-reply-to",
    references,
    "mime-version",
    "content-type",
    "content-transfer-encoding",
    precedence,
    "x-github-sender",
    "x-github-recipient",
    "x-github-reason",
    "list-id",
    "list-archive",
    "list-post",
    "list-unsubscribe",
    "x-auto-response-suppress",
    "x-github-recipient-address",
    "x-rcpt-to",
    "return-path"
)
5/29/15 2:12:04.516 AM Mail[3610]: *** Assertion failure in -[MCMessageHeaders headersForKey:], /SourceCache/Mail/Mail-2100/MailCore/Message/MCMessageHeaders.m:735
5/29/15 2:12:04.516 AM Mail[3610]: Use -messageIDListForKey: for message ID header keys
5/29/15 2:12:04.517 AM Mail[3610]: (
	0   CoreFoundation                      0x00007fff9282e03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff971f376e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff9282de1a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff90cf88cb -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   MailCore                            0x00007fff9260177d -[MCMessageHeaders headersForKey:] + 350
	5   ReplyWithHeader                     0x0000000115576854 ReplyWithHeader + 10324
	6   ReplyWithHeader                     0x000000011557aa7a ReplyWithHeader + 27258
	7   Mail                                0x000000010ee83948 Mail + 514376
	8   Mail                                0x000000010ee832f2 Mail + 512754
	9   Mail                                0x000000010ee80452 Mail + 500818
	10  CoreFoundation                      0x00007fff927057bc __invoking___ + 140
	11  CoreFoundation                      0x00007fff92705612 -[NSInvocation invoke] + 290
	12  MailCore                            0x00007fff92656a14 -[MCThrowingInvocationOperation main] + 48
	13  MailCore                            0x00007fff925e815e -[MCMainThreadInvocationOperation main] + 55
	14  Foundation                          0x00007fff90cc2d00 __NSThreadPerformPerform + 293
	15  CoreFoundation                      0x00007fff9274aa01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	16  CoreFoundation                      0x00007fff9273cb8d __CFRunLoopDoSources0 + 269
	17  CoreFoundation                      0x00007fff9273c1bf __CFRunLoopRun + 927
	18  CoreFoundation                      0x00007fff9273bbd8 CFRunLoopRunSpecific + 296
	19  HIToolbox                           0x00007fff986ef56f RunCurrentEventLoopInMode + 235
	20  HIToolbox                           0x00007fff986ef2ea ReceiveNextEventCommon + 431
	21  HIToolbox                           0x00007fff986ef12b _BlockUntilNextEventMatchingListInModeWithFilter + 71
	22  AppKit                              0x00007fff8b4dc98b _DPSNextEvent + 978
	23  AppKit                              0x00007fff8b4dbf38 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
	24  AppKit                              0x00007fff8b4d1bd3 -[NSApplication run] + 594
	25  AppKit                              0x00007fff8b44e324 NSApplicationMain + 1832
	26  libdyld.dylib                       0x00007fff8c0445c9 start + 1
	27  ???                                 0x0000000000000001 0x0 + 1
)
5/29/15 2:12:50.550 AM mDNSResponder[90]: _kerberos.Freds-Mac-Pro-2.279246790.members.btmm.icloud.com.: bad signature
5/29/15 2:12:50.550 AM mDNSResponder[90]: hndlRecordUpdateReply: Registration of record _kerberos.Freds-Mac-Pro-2.279246790.members.btmm.icloud.com. type 16 failed with error -65560
5/29/15 2:12:50.550 AM mDNSResponder[90]: Fred’s\032Mac\032Pro._device-info._tcp.279246790.members.btmm.icloud.com.: bad signature
5/29/15 2:12:50.551 AM mDNSResponder[90]: hndlRecordUpdateReply: Registration of record Fred’s\032Mac\032Pro._device-info._tcp.279246790.members.btmm.icloud.com. type 16 failed with error -65560
5/29/15 2:12:50.551 AM mDNSResponder[90]: _services._dns-sd._udp.279246790.members.btmm.icloud.com.: bad signature
5/29/15 2:12:50.551 AM mDNSResponder[90]: hndlRecordUpdateReply: Registration of record _services._dns-sd._udp.279246790.members.btmm.icloud.com. type 12 failed with error -65560
5/29/15 2:12:50.551 AM mDNSResponder[90]: _services._dns-sd._udp.279246790.members.btmm.icloud.com.: bad signature
5/29/15 2:12:50.551 AM mDNSResponder[90]: hndlRecordUpdateReply: Registration of record _services._dns-sd._udp.279246790.members.btmm.icloud.com. type 12 failed with error -65560
5/29/15 2:12:50.551 AM mDNSResponder[90]: _autotunnel.Freds-Mac-Pro-2.279246790.members.btmm.icloud.com.: bad signature
5/29/15 2:12:50.551 AM mDNSResponder[90]: hndlRecordUpdateReply: Registration of record _autotunnel.Freds-Mac-Pro-2.279246790.members.btmm.icloud.com. type 1 failed with error -65560
5/29/15 2:12:50.551 AM mDNSResponder[90]: _autotunnel._udp.Freds-Mac-Pro-2.279246790.members.btmm.icloud.com.: bad signature
5/29/15 2:12:50.551 AM mDNSResponder[90]: hndlRecordUpdateReply: Registration of record _autotunnel._udp.Freds-Mac-Pro-2.279246790.members.btmm.icloud.com. type 33 failed with error -65560

**Comment by jeevatkm** [comment]
@fmaxwell Thanks for your time. I'm sorry about back & forth. This is strange. Let's do following things to narrow down the problem. 

Step 1: Please turn off the RWH debug mode and Close Mail.app

<pre>defaults write com.apple.mail MHDebugLog -bool false</pre>

Step 2: Please download updated version v5.0-beta here ([http://docs.myjeeva.com/rwh/ReplyWithHeader-v5.0-beta.zip](http://docs.myjeeva.com/rwh/ReplyWithHeader-v5.0-beta.zip))
Step 3: Install newly downloaded RWH v5.0-beta
Step 4: Start Console.app; since I have made specific change, which will output log with prefix of <code>fmaxwell:: &lt;log message></code>
Step 5: Open Mail.app and please check Include all headers option in the RWH preferences
Step 6: Please do Reply/Reply All/Forward; Watch Console.app and share your feedback

Thanks again!

**Comment by fmaxwell** [comment]
First, no apologies are necessary!  You’re quickly implementing a feature that I requested and I am happy to help however I can (especially since I’m retired as of last year).  I’m assuming none of this exchange is making it into any public repository.

It works!  See below.  Could I have caused the problem previously by not restarting mail after the installation of RWH 5.0 beta?  If so, I apologize.

I did the following:

Downloaded the package
Installed it.
Turned off debugging
Shut down mail
Brought up the console
Cleared the console
Started mail.
Set preference to return all headers in reply.
Hit reply to your message.
Copied the console output, which appears below.

Below is the console output followed by the message:

5/29/15 3:19:46.073 PM com.apple.xpc.launchd[1]: (com.apple.imfoundation.IMRemoteURLConnectionAgent) The _DirtyJetsamMemoryLimit key is not available on this platform.
5/29/15 3:19:46.438 PM Mail[7491]: ReplyWithHeader v5.0-beta plugin loaded, OS X Version 10.10.4 (Build 14E26a)
5/29/15 3:19:46.438 PM Mail[7491]: ReplyWithHeader v5.0-beta debug log enabled: NO
5/29/15 3:19:47.188 PM com.apple.xpc.launchd[1]: (com.apple.imfoundation.IMRemoteURLConnectionAgent) The _DirtyJetsamMemoryLimit key is not available on this platform.
5/29/15 3:19:49.751 PM accountsd[396]: Enter ShareKitAccountEnabler  - didChangeWithType - type=2 for account apple@anti-spam.org (8605F1A0-2711-4F3F-91FB-60D47844B3AE).
5/29/15 3:19:49.752 PM accountsd[396]: AIDA Notification plugin running
5/29/15 3:19:49.000 PM kernel[0]: Sandbox: icbaccountsd(7496) deny mach-lookup com.apple.CrashReporterSupportHelper
5/29/15 3:19:49.953 PM icbaccountsd[7496]: Connection error while checking Apple Internalness. Error: Error Domain=NSCocoaErrorDomain Code=4099 "Couldn’t communicate with a helper application." (The connection to service named com.apple.CrashReporterSupportHelper was invalidated.) UserInfo=0x7ffc1cb00490 {NSDebugDescription=The connection to service named com.apple.CrashReporterSupportHelper was invalidated.}
5/29/15 3:19:49.000 PM kernel[0]: Sandbox: icbaccountsd(7496) deny file-read-data /Library/Preferences/com.apple.security-common.plist
5/29/15 3:19:50.592 PM com.apple.xpc.launchd[1]: (com.apple.imfoundation.IMRemoteURLConnectionAgent) The _DirtyJetsamMemoryLimit key is not available on this platform.
5/29/15 3:19:50.000 PM kernel[0]: Sandbox: com.apple.WebKit(7497) deny file-read-data /Library/Preferences/com.apple.security-common.plist
5/29/15 3:20:05.565 PM com.apple.xpc.launchd[1]: (com.apple.imfoundation.IMRemoteURLConnectionAgent) The _DirtyJetsamMemoryLimit key is not available on this platform.
5/29/15 3:20:38.733 PM Mail[7491]: fmaxwell:: Before cleanup allHeaderKeys:: (
    received,
    "dkim-signature",
    date,
    from,
    "reply-to",
    to,
    cc,
    "message-id",
    "in-reply-to",
    references,
    subject,
    "mime-version",
    "content-type",
    "content-transfer-encoding",
    precedence,
    "x-github-sender",
    "x-github-recipient",
    "x-github-reason",
    "list-id",
    "list-archive",
    "list-post",
    "list-unsubscribe",
    "x-auto-response-suppress",
    "x-github-recipient-address",
    "x-sg-eid",
    "x-rcpt-to",
    "return-path"
)
5/29/15 3:20:38.733 PM Mail[7491]: fmaxwell:: Key: reply-to, Values: jeevatkm/ReplyWithHeader <reply@reply.github.com>
5/29/15 3:20:38.733 PM Mail[7491]: fmaxwell:: After cleanup allHeaderKeys:: (
    received,
    "dkim-signature",
    "message-id",
    "in-reply-to",
    references,
    "mime-version",
    "content-type",
    "content-transfer-encoding",
    precedence,
    "x-github-sender",
    "x-github-recipient",
    "x-github-reason",
    "list-id",
    "list-archive",
    "list-post",
    "list-unsubscribe",
    "x-auto-response-suppress",
    "x-github-recipient-address",
    "x-sg-eid",
    "x-rcpt-to",
    "return-path"
)
5/29/15 3:20:38.734 PM Mail[7491]: *** Assertion failure in -[MCMessageHeaders headersForKey:], /SourceCache/Mail/Mail-2100/MailCore/Message/MCMessageHeaders.m:735
5/29/15 3:20:38.734 PM Mail[7491]: fmaxwell:: Error occured for header key [message-id], message is [Use -messageIDListForKey: for message ID header keys]
5/29/15 3:20:38.734 PM Mail[7491]: *** Assertion failure in -[MCMessageHeaders headersForKey:], /SourceCache/Mail/Mail-2100/MailCore/Message/MCMessageHeaders.m:735
5/29/15 3:20:38.734 PM Mail[7491]: fmaxwell:: Error occured for header key [in-reply-to], message is [Use -messageIDListForKey: for message ID header keys]
5/29/15 3:20:38.734 PM Mail[7491]: *** Assertion failure in -[MCMessageHeaders headersForKey:], /SourceCache/Mail/Mail-2100/MailCore/Message/MCMessageHeaders.m:735
5/29/15 3:20:38.734 PM Mail[7491]: fmaxwell:: Error occured for header key [references], message is [Use -messageIDListForKey: for message ID header keys]
5/29/15 3:20:38.735 PM Mail[7491]: fmaxwell:: Special header [(
    "2||message-id",
    "3||in-reply-to",
    "4||references"
)] handling in Yosemite for this message.
5/29/15 3:20:38.735 PM Mail[7491]: fmaxwell:: allHeaders:: (
    "References: <jeevatkm/ReplyWithHeader/issues/85@github.com>{\n}",
    "In-Reply-To: <jeevatkm/ReplyWithHeader/issues/85@github.com>{\n}",
    "Message-Id: <jeevatkm/ReplyWithHeader/issues/85/106905063@github.com>{\n}",
    "Reply-To: jeevatkm/ReplyWithHeader <reply@reply.github.com>{\n}",
    "Received: from o1.sgmail.github.com ([192.254.114.176]) by anti-spam.org with MailEnable ESMTP; Fri, 29 May 2015 15:06:56 -0400,\nby filter0432p1mdw1.sendgrid.net with SMTP id filter0432p1mdw1.8540.5568B8BE26 2015-05-29 19:06:38.973257447 +0000 UTC,\nfrom github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16]) by ismtpd-049 (SG) with ESMTP id 14da111a9b5.7f7b.a67e44 for <_github@mail2fm.com>; Fri, 29 May 2015 19:06:38 +0000 (UTC){\n}",
    "Dkim-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com;  h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe;  s=s20150108; bh=zGHXpsDZ3iDX21BCWCm/eG5lOZM=; b=F307ozBhrw4HZbkn tPkeIqRPFOjlMWvy901fmBaW8nSkYKWxlZy7zXFPPcEqZr2SXzdCQlXupBGTuz+h 3bF7FIYDfXqn6GdPHQ4sFIvO4Fys6A3RGKxn1OjOzg10W6v6eDU5UJ8RNALrI8qp ZJMHdRSOLxRnK8RGcxRwPc4C6rk={\n}",
    "Mime-Version: 1.0{\n}",
    "Content-Type: multipart/alternative; boundary=\"--==_mimepart_5568b8bbd7314_362e3fe48d8f729c58734e\"; charset=UTF-8{\n}",
    "Content-Transfer-Encoding: 7bit{\n}",
    "Precedence: list{\n}",
    "X-Github-Sender: jeevatkm{\n}",
    "X-Github-Recipient: fmaxwell{\n}",
    "X-Github-Reason: mention{\n}",
    "List-Id: jeevatkm/ReplyWithHeader <ReplyWithHeader.jeevatkm.github.com>{\n}",
    "List-Archive: https://github.com/jeevatkm/ReplyWithHeader{\n}",
    "List-Post: <mailto:reply@reply.github.com>{\n}",
    "List-Unsubscribe: <mailto:unsub+00be96f2520a94770d7bb977485e8d63ca902867d583461692cf0000000111807abb92a169ce049ebd10@reply.github.com>, <https://github.com/notifications/unsubscribe/AL6W8tzBoNFaFog47kOFSnlx0g5LvM06ks5oOLA7gaJpZM4EeXDp>{\n}",
    "X-Auto-Response-Suppress: All{\n}",
    "X-Github-Recipient-Address: _github@mail2fm.com{\n}",
    "X-Sg-Eid: MVHBdNM75wQYcxyaK1uJsjKWXpQ0SNSrx0/P58oqSeZ9mOW0qX+eTqgLlp36qAetzl+7Eq2hf02+JO 1XBg9vHs/tdflH4sXxQY9Zx555NVsyZc6y3h8dYtCqfc5A9j7NVf3lkGaVJwo51gOEaC8N4mBVLx9w 6568RJS5wE+mGZM={\n}",
    "X-Rcpt-To: <_github@mail2fm.com>{\n}",
    "Return-Path: <bounces+848413-a856-_github=mail2fm.com@sgmail.github.com>{\n}"
)

**Comment by jeevatkm** [comment]
I'm happy it's working for you :) yes Mail.app requires restart every time after any plugin installation (including RWH).

Coming to your concern, Github makes every conversation about this issue as public. Please have a look on this page https://github.com/jeevatkm/ReplyWithHeader/issues/85 and let me know. So I clean up private thing into <code>[............]</code> 

For private/direct conversation, please use my email id jeeva@myjeeva.com.

**Comment by fmaxwell** [comment]
I am sorry that I cost you so much time.  I installed and the preferences were immediately available, so I did not know.  

I’m used to the Firefox model where most plugins work without restart and those that require restart clearly indicate it.  You may wish to modify your install script to tell the user to restart mail.

Thanks so much.  You’ve provided a tool that’s going to be invaluable for those of us who have to, or choose to, report spam, phishing, and malware spread through email.

**Comment by jeevatkm** [comment]
I'm glad it worked for you, Thanks. Let me know if you come across any issue.
