### ISSUE TITLE
"reply-all" disabled with upgrade in Mac OS X Lion

### ISSUE THREAD

**Issue by stultitia** [jeevatkm/ReplyWithHeader#87]
Before I upgraded to latest version, "reply-all" button was working. After upgrade, I noticed it was not working. I tried other stuff (including disabling your add-on) to no avail; and finally decided to remove your add-on. After uninstalling and restarting the Mail app, "reply-all" works again, so I have to presume your add-on is causing the issue.

Macbook Pro early 2011 OS X 10.7.5 - Mail 5.3 (1283)

Do you need any other info?

**Comment by jeevatkm** [comment]
Thanks for reporting an issue. Do you see any errors in Console.app for Mail app? If you notice then can you please share those?

**Comment by stultitia** [comment]
15.06.2015 17:51:42,168 Mail: -[AddressTextField addresses]: unrecognized selector sent to instance 0x7fc768c346c0
15.06.2015 17:51:42,168 Mail: -[AddressTextField addresses]: unrecognized selector sent to instance 0x7fc768c346c0
15.06.2015 17:51:42,169 Mail: (
	0   CoreFoundation                      0x00007fff8c353f56 __exceptionPreprocess + 198
	1   libobjc.A.dylib                     0x00007fff8e0d5d5e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8c3e01be -[NSObject doesNotRecognizeSelector:] + 190
	3   CoreFoundation                      0x00007fff8c340e23 ___forwarding___ + 371
	4   CoreFoundation                      0x00007fff8c340c38 _CF_forwarding_prep_0 + 232
	5   ReplyWithHeader                     0x0000000112728bad ReplyWithHeader + 48045
	6   ReplyWithHeader                     0x0000000112728764 ReplyWithHeader + 46948
	7   Mail                                0x000000010d17063d Mail + 710205
	8   Mail                                0x000000010d1701ee Mail + 709102
	9   Mail                                0x000000010d16caa1 Mail + 694945
	10  Mail                                0x000000010d303f15 Mail + 2363157
	11  AppKit                              0x00007fff899b4d5e -[NSWindow sendEvent:] + 6504
	12  Mail                                0x000000010d142e0b Mail + 523787
	13  AppKit                              0x00007fff8994e3a5 -[NSApplication sendEvent:] + 5593
	14  Mail                                0x000000010d142aef Mail + 522991
	15  AppKit                              0x00007fff898e4a0e -[NSApplication run] + 555
	16  AppKit                              0x00007fff89b60eac NSApplicationMain + 867
	17  Mail                                0x000000010d19b300 Mail + 885504
)

**Comment by jeevatkm** [comment]
Thanks, will get back to as soon as!

**Comment by jeevatkm** [comment]
I have applied quick fix here is a download link:
https://app.box.com/s/uvtnc5e6aaxlnh40lhltw0x3mm5qq6mv

Please let me know!

**Comment by stultitia** [comment]
OK I tested it to reply to your email now, and it seems to work properly.

Thanks and cheers!

**Comment by jeevatkm** [comment]
You're welcome.

**Comment by stultitia** [comment]
Actually it's not working again.

And this time I realized, when I quit Mail.app and repoen it, the email appears as if the button worked. I mean:
-I click the button ("reply-all", "reply", "forward"; none of them work)
-no email appears, to be sent
-I close Mail.app
-I repoen it
-now the "reply-all" (and also "forward" and "reply") email(s) that was supposed to appear, appears.

Here is the console before closing Mail.app:

16.06.2015 22:27:05,871 Mail: RWH:: Unable to parse date [-[__NSCFString replaceCharactersInRange:withString:]: nil argument]
16.06.2015 22:27:05,874 Mail: NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds
16.06.2015 22:27:05,875 Mail: (
	0   CoreFoundation                      0x00007fff916bbf56 __exceptionPreprocess + 198
	1   libobjc.A.dylib                     0x00007fff9343dd5e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff916bbd8a +[NSException raise:format:arguments:] + 106
	3   CoreFoundation                      0x00007fff916bbd14 +[NSException raise:format:] + 116
	4   Foundation                          0x00007fff97360269 -[NSRLEArray objectAtIndex:effectiveRange:] + 117
	5   Foundation                          0x00007fff97362f8a -[NSConcreteMutableAttributedString attributesAtIndex:effectiveRange:] + 29
	6   Foundation                          0x00007fff97367961 -[NSMutableAttributedString addAttributes:range:] + 161
	7   ReplyWithHeader                     0x000000010c495d84 ReplyWithHeader + 7556
	8   ReplyWithHeader                     0x000000010c499774 ReplyWithHeader + 22388
	9   ReplyWithHeader                     0x000000010c49b5e8 ReplyWithHeader + 30184
	10  Mail                                0x0000000106eac333 Mail + 787251
	11  Mail                                0x0000000106eab411 Mail + 783377
	12  Mail                                0x0000000106eab1aa Mail + 782762
	13  CoreFoundation                      0x00007fff916adefc __invoking___ + 140
	14  CoreFoundation                      0x00007fff916add94 -[NSInvocation invoke] + 132
	15  Message                             0x00007fff93c23655 -[ThrowingInvocationOperation main] + 33
	16  Message                             0x00007fff93cfcba4 -[MainThreadInvocationOperation main] + 85
	17  CoreFoundation                      0x00007fff916ab70d -[NSObject performSelector:withObject:] + 61
	18  Foundation                          0x00007fff9733ed70 __NSThreadPerformPerform + 214
	19  CoreFoundation                      0x00007fff9162a4f1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	20  CoreFoundation                      0x00007fff91629d5d __CFRunLoopDoSources0 + 253
	21  CoreFoundation                      0x00007fff91650b49 __CFRunLoopRun + 905
	22  CoreFoundation                      0x00007fff91650486 CFRunLoopRunSpecific + 230
	23  HIToolbox                           0x00007fff923ed2bf RunCurrentEventLoopInMode + 277
	24  HIToolbox                           0x00007fff923f456d ReceiveNextEventCommon + 355
	25  HIToolbox                           0x00007fff923f43fa BlockUntilNextEventMatchingListInMode + 62
	26  AppKit                              0x00007fff8ec50779 _DPSNextEvent + 659
	27  AppKit                              0x00007fff8ec5007d -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 135
	28  AppKit                              0x00007fff8ec4c9b9 -[NSApplication run] + 470
	29  AppKit                              0x00007fff8eec8eac NSApplicationMain + 867
	30  Mail                                0x0000000106ec4300 Mail + 885504
	31  ???                                 0x0000000000000002 0x0 + 2
)

And this is after reopening it -I don't know if this also has anything to do with RWH:

16.06.2015 22:30:33,557 Mail: Exception writing metadata: CoreData could not fulfill a fault for '0x7fd133165c90 <x-coredata://36C83AB7-A9A2-406E-8825-79AB571B1A1C/ABCDPhoneNumber/p5290>'

Best

**Comment by jeevatkm** [comment]
First one is related with RWH and second one is not.  As per first exception i.e. date parsing error, it is strange and also it looks like cache issue of Mail.app.

How about having remote screen share to figure out the issue? If Yes then we talk about time details.

**Comment by marcodome** [comment]
Hi,
I have the same problem upgrading from 4.9 to 5.0; I downgraded to 4.9 again and now it works.
I use Mountain Lion 10.8.5 with Apple Mail 6.6 (1510).
Which information can I give you to track down the issue?

Regards and thank you
Marco

**Comment by jeevatkm** [comment]
@marcodome Can you please try this one https://app.box.com/s/uvtnc5e6aaxlnh40lhltw0x3mm5qq6mv and share your feedback?

Also I will analyze in the meantime.

**Comment by marcodome** [comment]
Thank you for the aswer: It works but it has a strange graphic effect: in the moment between I click the button and the window with the email is shown, the mail windows flashes a little bit.
I prefer the 4.9 :-/

**Comment by jeevatkm** [comment]
Okay, please use 4.9 for a while. I'm working on it once done I will share it with you for a feedback.

**Comment by jeevatkm** [comment]
Releasing updated v5.1-beta http://bit.ly/1LouEKr.

**Comment by stultitia** [comment]
Thanks! It looks like it works fine. And sorry for not remote sharing my screen; I was busy and I forgot to write a reply and then I forgot and then I remembered now as I checked the previous messages.

Best.

**Comment by marcodome** [comment]
Thank you: in the meantime I've upgraded to Yosemite and 5.0 works fine :-)
Best Regards,
Marco

**Comment by stultitia** [comment]
Thanks for the new release. I hope all these are sorted out. I'll write again if I encounter any issues. I plan on moving on to El Capitan soon anyways though; that might be a bit of a refresh for me:))

Thanks again

**Comment by jeevatkm** [comment]
Yes, it is sorted out. El capitan looks good. Feel free to report if you come across any issues. Thanks.
