### ISSUE TITLE
Date Format in v5

### ISSUE THREAD

**Issue by MrO007** [jeevatkm/ReplyWithHeader#88]
Hello,

Does the Date format in the RWH still following the regional setting?  It seems to have changed from:

Sent: 17 June 2015 11:39:10 BST

to

Sent: Thursday, Jun 18, 2015 at 3:45:28 PM GMT+1

The top one looks more natural to Outlook in the UK.

Cheers,
Mike

**Comment by jeevatkm** [comment]
Yes, added the international date format. Now I feel, it's good to provide an option in RWH preferences. 
I will bring an option to select localized and international date format in v5.1, sorry for inconvenience. 

- Jeeva

**Comment by jeevatkm** [comment]
And one more thing. v5.0 has week day info like Outlook.

**Comment by jeevatkm** [comment]
Would you like to try v5.1-beta and share feedback on that?

**Comment by MrO007** [comment]
Sure, does 5.1 also fix the Reply All issue?

Regards,
Mike

**Comment by jeevatkm** [comment]
No, I'm working on reply-all issue. Once done let you know.

**Comment by MrO007** [comment]
Thanks very much, I'll gladly test for you.

**Comment by jeevatkm** [comment]
Releasing updated v5.1-beta http://bit.ly/1LouEKr.

**Comment by MrO007** [comment]
Hey jeevatkm, apologies, I tried to respond and it didn't show, the date format with the new version didn't pull the local daylight savings timezone.

With the two options you created, I get either:

Sent: August 27, 2015 at 4:45:03 PM GMT+1  <-- Should be BST

Or

Sent: August 27, 2015 at 3:45:03 PM GMT

**Comment by jeevatkm** [comment]
@MrO007 No need to apologies, everyone busy with their work :)

I would like to know more on this. Since default date format as per v4.9 before approach and GMT is introduced in v5.0 just improved that.

Shall we have screen share to figure out or for me to understand better to addressed the issue?

**Comment by jeevatkm** [comment]
If you don't mind, can you please try it once more for date format. I just uploaded the new one (use same download link). I think I misplaced the one line that might have caused GMT+1 instead of BST.

I'm sorry about taking more time from you.
