### ISSUE TITLE
24h clock format switch, no GMT suffix

### ISSUE THREAD

**Issue by GHubbler** [jeevatkm/ReplyWithHeader#91]
It would be great, if you could implement 12/24h global switch for clock time independent of the current language setting. E.g. I would like to have the english attributions but also want 24h clock format.

It does not read out the proper system settings of my OS X.

Another improvement would be a setting that would allow to disable the GMT-suffix after the time. It is mostly annoying and useless either.

E.g.:
August 27, 2015 at 1:52:16 PM GMT+2

should become
27th of August 2015 at 13:52

or even better: Use the long format of the regional settings in OS X system settings.

**Comment by jeevatkm** [comment]
RWH uses system regional Long format settings by default (same as Mail.app behavior) and GMT is format is supported. 

Due to limitation, I did possible things in the plugin. I hope this is close by to your expectation.
