### ISSUE TITLE
Settings dialog is cutted at the bottom

### ISSUE THREAD

**Issue by GHubbler** [jeevatkm/ReplyWithHeader#92]
In El Capitan the settings dialog is not fully visible on my 11" Macbook Air.
![settings](https://cloud.githubusercontent.com/assets/10322831/10223827/5e4b4796-685b-11e5-825a-69073cf4131c.png)

**Comment by jeevatkm** [comment]
@GHubbler Thanks for reporting an issue. I will surely address this one before v5.1 release.

I would like ask you one thing, could you please confirm RWH is working okay with El Capitan public release?

I know you have raised an another issue for Date requirements, will surely addressed those in upcoming release. However I have to make a release of working plugin for users, so they can benefit from El Capitan OS usage.

**Comment by jeevatkm** [comment]
Done!
