### ISSUE TITLE
Small Dutch translation issue

### ISSUE THREAD

**Issue by timvdsm** [jeevatkm/ReplyWithHeader#93]
Hi,
I just want to mention a very small translation issue in the Dutch (Nederlands) Reply Header language.
This is the existing reply header translation:
Van: xxx
Verstuurd: 1 oktober 2015 19:28:52 CEST
To: xxx
Onderwerp: xxx

But it should be this when using outlook's example:
Van: xxx
Datum: donderdag 1 oktober 2015 19:28
Aan: xxx
Onderwerp: xxx

Many thanks for this great tool! I'm testing the beta version now on El Capitan.

**Comment by jeevatkm** [comment]
Thanks @timvdsm, will incorporate it.

**Comment by jeevatkm** [comment]
Done!

**Comment by timvdsm** [comment]
Hi many thanks,
Can I download the update somewhere?

Regards,
Tim

**Comment by jeevatkm** [comment]
@timvdsm - Yes you can download it from here http://docs.myjeeva.com/rwh/ReplyWithHeader-v5.1-beta.zip
