### ISSUE TITLE
Header not added to forwarded mails in TB ver. 45.1.0

### ISSUE THREAD

**Issue by mariobig** [jeevatkm/ReplyWithHeader#96]
Hi,

This nice plugin does not work properly with TB ver 45.1.0. It does not attach header to forwarded mails. It works OK with replied mails.

**Comment by jeevatkm** [comment]
This is belongs to RWH Mozilla plugin. Doesn't belong here. Please create an issue [here](https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues).
